### ISSUE TITLE
SequenceRecorder todo

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#172]
- [x] Crop
- [x] state parmeter does not work. Nothing is set by the parameter. Still need to set the state using the webUI.
- [x] Ranges for webUI object not working.
- [x] Fix load function. Load on start works but button crashes ikaros.
- [x] Validate file on load
- [x] Group function for channels
- [ ] Make sliders inactive if not connected using internal control parameter
- [ ] Make play buttons inactive if nothing recorded
- [x] Adding and renaming sequences
- [x] Trigger function
- [x] Store mode of sequence. 
- [x] Slider for internal controlled channels does not move in play state.
- [x] Non linear interpolation between key points. Like for sound channel. Keypoint A (sound trigger number 3) to Keypoint B (sound trigger number 10) should not trigger all the sound between 3 and 10.
- [x] Use ranges in plot
- [ ] More efficient plotting
- [ ] Do not send links to WebUI
- [x] Trigger grid WebUI widget
- [x] Remove single keypoint
- [x] Delete keypoints in range
- [ ] Simplify keypoints
- [ ] Smoothing
- [ ] Graph for longer sequences
- [ ] Add current filename to the view.
- [ ] Color code channels or hover to see the channel name.
- [ ] 
Bugs:
- [ ] WebUI plot not showing all points with mixing keyframe and live recording. Do key point recording on one channel. Live record another channel and the first channels plot is not there. The robot moves as expected.
- [ ]

**Comment by ikaros-project** [comment]
Cannot reproduce nan outputs.

**Comment by birgerjohansson** [comment]
Me neither.

**Comment by ikaros-project** [comment]
Moved.
